name: fterm
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  collection: ^1.16.0
  dio: ^5.1.1

  fluentui_system_icons: ^1.1.186
  flutter_hooks: ^0.18.5+1
  flutter_pty: ^0.4.0
  flutter_spinbox: ^0.13.0
  flutter_svg: ^2.0.5

  flutter:
    sdk: flutter

  fuzzywuzzy: ^1.1.6
  go_router: ^9.0.0
  hooks_riverpod: ^2.1.1
  http: ^1.1.0
  logging: ^1.1.0
  multi_split_view: ^2.1.0
  nanoid: ^1.0.0
  package_info_plus: ^4.0.2
  path: ^1.8.2
  riverpod: ^2.1.1
  scroll_to_index: ^3.0.1
  shared_preferences: ^2.0.15
  stack_trace: ^1.10.0
  tuple: ^2.0.1
  url_launcher: ^6.1.7
  version: ^3.0.2
  window_manager: ^0.3.2

  window_size:
    git:
      path: plugins/window_size
      ref: 6c66ad23ee79749f30a8eece542cf54eaf157ed8
      url: https://github.com/google/flutter-desktop-embedding.git

  xterm: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
  fonts:
    - family: Fira Mono
      fonts:
        - asset: fonts/FiraMono-Regular.ttf
        - asset: fonts/FiraMono-Medium.ttf
        - asset: fonts/FiraMono-Bold.ttf
    - family: Monoton
      fonts:
        - asset: fonts/Monoton-Regular.ttf
    - family: Redhat Mono
      fonts:
        - asset: fonts/RedHatMono-Regular.ttf
        - asset: fonts/RedHatMono-Bold.ttf
        - asset: fonts/RedHatMono-BoldItalic.ttf
        - asset: fonts/RedHatMono-Italic.ttf
        - asset: fonts/RedHatMono-Light.ttf
        - asset: fonts/RedHatMono-LightItalic.ttf
        - asset: fonts/RedHatMono-Medium.ttf
        - asset: fonts/RedHatMono-MediumItalic.ttf
        - asset: fonts/RedHatMono-SemiBold.ttf
        - asset: fonts/RedHatMono-SemiBoldItalic.ttf